# Generated by Django 4.2 on 2023-05-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_accessrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='category',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
